### ISSUE TITLE
Go: failed to create new OS thread (have 5 already; errno=11)

### ISSUE THREAD

**Issue by nekketsuuu** [melpon/wandbox#306]
When I tried to run Go's hello-world program (from "Load template"), it returned the following error:

```
Start
go tool compile: exit status 2
runtime: failed to create new OS thread (have 5 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

runtime stack:
runtime.throw(0xe7936d, 0x9)
	/opt/wandbox/go-1.14.2/src/runtime/panic.go:1116 +0x72
runtime.newosproc(0xc000080000)
	/opt/wandbox/go-1.14.2/src/runtime/os_linux.go:161 +0x1ba
runtime.newm1(0xc000080000)
	/opt/wandbox/go-1.14.2/src/runtime/proc.go:1753 +0xdc
runtime.newm(0xe9e9b0, 0xc000021000)
	/opt/wandbox/go-1.14.2/src/runtime/proc.go:1732 +0x8f
runtime.startm(0x0, 0xc00001e801)
	/opt/wandbox/go-1.14.2/src/runtime/proc.go:1869 +0x12a
runtime.wakep(...)
	/opt/wandbox/go-1.14.2/src/runtime/proc.go:1953
runtime.resetspinning()
	/opt/wandbox/go-1.14.2/src/runtime/proc.go:2415 +0x93
runtime.schedule()
	/opt/wandbox/go-1.14.2/src/runtime/proc.go:2527 +0x2de
runtime.mstart1()
	/opt/wandbox/go-1.14.2/src/runtime/proc.go:1104 +0x8e
runtime.mstart()
	/opt/wandbox/go-1.14.2/src/runtime/proc.go:1062 +0x6e

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0xe9e810, 0xc00004a058, 0x170e, 0x2)
	/opt/wandbox/go-1.14.2/src/runtime/proc.go:304 +0xe0
runtime.chanrecv(0xc00004a000, 0x0, 0xc000000101, 0x418ace)
	/opt/wandbox/go-1.14.2/src/runtime/chan.go:525 +0x2e7
runtime.chanrecv1(0xc00004a000, 0x0)
	/opt/wandbox/go-1.14.2/src/runtime/chan.go:407 +0x2b
runtime.gcenable()
	/opt/wandbox/go-1.14.2/src/runtime/mgc.go:216 +0x95
runtime.main()
	/opt/wandbox/go-1.14.2/src/runtime/proc.go:166 +0x115
runtime.goexit()
	/opt/wandbox/go-1.14.2/src/runtime/asm_amd64.s:1373 +0x1
1
Finish
```

I suppose this is not a bug of the program, but an issue of runtime of Wandbox.

**Comment by nekketsuuu** [comment]
I confirmed a similar error is reproducible for Go 1.10, 1.11.13, 1.12.17, 1.13.10, 1.14.2, and HEAD devel +53f2, but **not** repro for 1.5.4, 1.6.3, 1.7.5, 1.8.3, 1.9.

**Comment by melpon** [comment]
実行可能なプロセス（スレッド）数を 16 に制限したせいですね。Go 環境ではもう少し増やすことにします。

**Comment by melpon** [comment]
修正して無事動くようになったので閉じます
